### ISSUE TITLE
rpi-v8 Node.js using a deprecated image

### ISSUE THREAD

**Issue by Nornode** [node-red/node-red-docker#120]
Hello! 
I just pulled a new image "nodered/node-red-docker:rpi-v8" and noticed that the node.js version used is outdated. It's also stated here: (https://hub.docker.com/r/hypriot/rpi-node/)
The new image should probably be: https://hub.docker.com/r/arm32v7/node/

Welcome to Node-RED
===================

2 Jul 10:39:09 - [info] Node-RED version: v0.20.6
2 Jul 10:39:09 - [info] Node.js  version: v8.1.3
2 Jul 10:39:09 - [info] Linux 4.14.98-v7+ arm LE
2 Jul 10:39:10 - [info] Loading palette nodes

Many thanks!

**Comment by MrAdam** [comment]
This is an issue when working with https://flows.nodered.org/node/node-red-contrib-home-assistant-websocket, as this requires Node.js v8.12+!

**Comment by xalexslx** [comment]
Any fix for this?

**Comment by diversit** [comment]
There are other plugins which _do_ require Node v10 already, like the Hue-magic plugin.
Since I'm using this plugin, and not the home-assistent-websocket plugin, I'm having issues because there is no Rpi image with Node v10.

So why not just provide an Rpi-V10 image and let the user choose which one to use based on the plugins he/she wants to use?

**Comment by knolleary** [comment]
@diversit because we don't have infinite resources to do everything instantly.

There is a PR in progress that completely reworks how we build the Docker images which brings Node 10 to the pi - https://github.com/node-red/node-red-docker/pull/124

**Comment by kymodoke** [comment]
I've pulled "nodered/node-red-docker:rpi-v8" to create a container and I've got that problem too that Nodered is complaining about outdated version of Node...

As a workaround, I connected to the console of that container as root, then typed these three lines

`npm cache clean -f
npm install -g n
n stable`

and voilà, as result:
`node -v
v10.16.3`

And Node-red is working great since ;)

**Comment by RaymondMouthaan** [comment]
Hi guys, i am the creator of PR #127, if you guys like to try node-red images which are based upon #127, i like to invite you to check out my [docker hub](https://cloud.docker.com/repository/docker/raymondmm/node-red/general).

How to use the images can be found in the [README](https://github.com/RaymondMouthaan/node-red-docker/blob/master/README.md)

**Comment by RaymondMouthaan** [comment]
Very soon Node-RED v1.0 including the Docker images and manifest list get released. With that this issue should be solved.

There are a few changes to the new release, please read the [README](https://github.com/node-red/node-red-docker/blob/master/README.md) for further details.

~ Team Node-RED ~
