### ISSUE TITLE
Please add the VOLUME tag back in to the dockerfile!

### ISSUE THREAD

**Issue by spants** [node-red/node-red-docker#18]
I can not set a local external directory on Docker OSX (kitematic) if there is no VOLUME tag in the dockerfile. I noticed that it was taken out in Sept 2016- any idea why?

**Comment by jthomas** [comment]
Can you provide me with the exact command-line you are using to run the container? 

Do you know that you can use command-line flags to set a volume as well (https://github.com/node-red/node-red-docker#host-directory-as-volume)?

We removed the VOLUME directive from the Dockerfile due to an issue with persisting changes to a new image (https://github.com/node-red/node-red-docker/issues/7). There wasn't any benefit to keeping the VOLUME directive in the file as this can be set on the command-line.

**Comment by spants** [comment]
I can add a volume manually with the -V switch but if you use kitematic gui for docker on Mac it will not let you assign a volume in the gui if the volume tag is not present in the dockerfile

**Comment by jthomas** [comment]
Thanks for the update, I can see this is a known issue for Kitematic (https://github.com/docker/kitematic/issues/376). 

We removed the VOLUME tag due to the following issue (#7). I understand this causes an issue for you but we won't revert this fix to resolve a bug that is in one particular Docker client.

Are you able to use the command-line Docker client to run the containers? If that isn't possible, you would have to fork this repository and build your own image. I'm going to close this issue as we won't be pushing a fix for this due to the reasons outlined above.

Thanks for reporting this, I can understand it's frustrating.
