### ISSUE TITLE
festival

### ISSUE THREAD

**Issue by mecko** [node-red/node-red-docker#192]
### What happens?
`festival` is not available under alpine's `apk`.
it takes forever to compile, if it even compiles, and would still require changing the docker image.
this makes the docker setup irrelevant.

### What do you expect to happen?
use a base image that supports widely used features or incorporate widely used features like festival in the docker build.

**Comment by knolleary** [comment]
The README explains about our choice of base image and what routes are available to you:

> The Node-RED images are based on official Node JS Alpine Linux images to keep them as small as possible. Using Alpine Linux reduces the built image size, but removes standard dependencies that are required for native module compilation. If you want to add dependencies with native dependencies, extend the Node-RED image with the missing packages on running containers or build new images see [docker-custom](https://github.com/node-red/node-red-docker/blob/master/docker-custom/README.md).

Given no-one has ever asked about Festival in relation to this images before, then its hard to judge how much actual demand there is. So we're not going to change the default base image due to this one request.

There is an open question over whether we could also build ubuntu based images alongside the default alpine ones - but that then becomes an ever increasing matrix of images/archs/platforms for us to maintain.

**Comment by dceejay** [comment]
for the uninitiated - what is Festival ? somewhat hard to search for...

**Comment by knolleary** [comment]
Took me a big of googling to narrow it down, but I assume its this: https://wiki.archlinux.org/index.php/Festival

**Comment by janvda** [comment]
@mecko: I don't think "Festival" is part of any linux package repository (so the issue is not specific for the alpine image upon which the node-red docker image is based on).


```
it takes forever to compile, if it even compiles
```

If there are compilation issues then it is better to report these in https://github.com/festvox/festival and share the actual details of the compilation issues you are facing.

```
..., and would still require changing the docker image.
this makes the docker setup irrelevant.
```

I don't agree.  In this specific case I would expect that you create a dockerfile that is starting from the node-red docker image (e.g. first line of your dockerfile is something like `FROM nodered/node-red`) and then have a look at 
* https://forums.docker.com/t/best-practices-for-git-clone-make-etc-via-dockerfile-run/79152

**Comment by mecko** [comment]
> I don't think "Festival" is part of any linux package repository (so the issue is not specific for the alpine image upon which the node-red docker image is based on).

If nothing else, then at least [Ubuntu does](https://launchpad.net/ubuntu/trusty/+package/festival). I actually have festival installed using apt-get on the host running Raspbian, and it was working fine before I moved node-red to a docker container.

> If there are compilation issues then it is better to report these in https://github.com/festvox/festival and share the actual details of the compilation issues you are facing.

Like I said, it just takes forever, especially on low-end hardware that would typically run node-red (like a Raspberry Pi). It's not something to be reported. I was just mentioning that as a side effect that makes "self building" things a little unreasonable, at least in my case.

> I would expect that you create a dockerfile that is starting from the node-red docker image (e.g. first line of your dockerfile is something like `FROM nodered/node-red`)

Yes and no. This would _theoretically_ work, because that is essentially taking the current image and making custom changes to it. In practice, however, it's based on alpine, which doesn't have festival in its package repositories, so the only viable "change" to be done is manually compile festival and its companion software, which as mentioned above, isn't an actual option.

**Comment by RaymondMouthaan** [comment]
> > Yes and no. This would _theoretically_ work, because that is essentially taking the current image and making custom changes to it. In practice, however, it's based on alpine, which doesn't have festival in its package repositories, so the only viable "change" to be done is manually compile festival and its companion software, which as mentioned above, isn't an actual option.
> 
> I understand that compiling festival takes a long time on a raspberry pi , but if the compilation is done in the Dockerfile as I suggested then this should be done only once. From then on you can stop/start/restart the container without any need to recompile festival. So isn't this a viable option and if not why not ?

Even once `the forever taking` compile process is done, the festival package can be stored out side the container who build it. The build container can be removed, a new container can be deployed, the festival package copied back into the new container and installed. To have a clean running container without all required deps etc festival needs to compile.

**Comment by dceejay** [comment]
I have added an example dockerfile.debian to the dev branch - So you could maybe try building a custom image based on that ?

**Comment by mecko** [comment]
> 
> 
> I have added an example dockerfile.debian to the dev branch - So you could maybe try building a custom image based on that ?

Thank you for your effort, this certainly helps.

You might want to change alpine to debian in https://github.com/node-red/node-red-docker/blob/d18f6e11269580f0eb9d20a55400b829ab900de5/docker-custom/Dockerfile.debian#L56
