### ISSUE TITLE
Update nodered/node-red:1.1.3-12 to "really" use the latest node 12 (and thus the latest alpine)

### ISSUE THREAD

**Issue by T0T4R4** [node-red/node-red-docker#196]
The  image 
    nodered/node-red:1.1.3-12
currently specifically uses node 12.16.3
    node/node:12.16.3-alpine
which is 4 months old, and a bit inconsistent considering the fact that the node-red tag does not specify this version of node exactly. We would expect the node-red image to use "12" which means the latest...

Would it be possible to point it to the latest v12 and latest alpine instead ?
node/node:12-alpine

Interestingly enough, the docker.custom file already states 12 as default 
![image](https://user-images.githubusercontent.com/1294511/90715751-89c98280-e2ee-11ea-8d89-cf15623b3a90.png)

**Comment by janvda** [comment]
Strange.
Which architecture are you using ?

I am also using image `nodered/node-red:1.1.3-12` on my intel-nuc device
and this is what I see in the log file:
```
Copying settings.js to /data folder
Starting node-red ...
> node-red-docker@1.1.3 start /usr/src/node-red
> node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"
18 Aug 09:15:46 - [info] 
Welcome to Node-RED
===================
18 Aug 09:15:46 - [info] Node-RED version: v1.1.3
18 Aug 09:15:46 - [info] Node.js  version: v12.18.3
18 Aug 09:15:46 - [info] Linux 4.18.0-193.6.3.el8_2.x86_64 x64 LE
18 Aug 09:15:46 - [info] Loading palette nodes
...
```

**Comment by RaymondMouthaan** [comment]
Node-RED images are based on the Alpine based images provided by Node. For example for arch `arm32v7` and tag `12-alpine` [this](https://hub.docker.com/layers/arm32v7/node/12-alpine/images/sha256-ab58814a31480be66de2f73d233d74f9d9a2761c3ed30ea4445e01f034dd2f58?context=explore) is the latest image for arm32v7 & Alpine & Node, so when NR images are build we alway build them based on the latest image Node provides. In practice this could mean that when NR hasn't released for a while, the Node version as well as the Alpine version in the Node-RED container is behind.

If you like to be up2date with the latest versions of Alpine, Node and all installed packages, I would recommend building your own Docker image (see Docker custom documentation) or update the container manually with the appropriate alpine commands and node commands, with the side note to loose all update once you redeploy the container.

Node-RED images are tagged on Node-RED version, major version of Node, architecture and latest to keep tags readable. Generally speaking one only needs latest or even leave out the tag when deploying, since Node-RED images are manifest listed and latest is Node v12, Docker pulls the most recent image for you for your architecture.

**Comment by dceejay** [comment]
Closing as we don't intend to start rebuilding all the images all the time, only when we release Node-RED releases or updates. "latest-12" will give us a consistent install across users at that release level. If necessary we will do v1.1.3-2 -3 etc for updates that affect docker part of the project only.
