### ISSUE TITLE
image uses an almost outdated alpine 3.12 with end of support on 2022-05-01

### ISSUE THREAD

**Issue by mx-bernhard** [node-red/node-red-docker#310]
### What happens?

Image [`nodered/node-red`](https://github.com/node-red/node-red-docker/blob/3b0329ad9253409da0633074147c2d47af2fbf00/docker-custom/docker-alpine.sh#L12) uses an almost outdated alpine version 3.12 which will reach end of support on [2022-05-01](https://www.alpinelinux.org/releases/).

### What do you expect to happen?

Image is based on a newer version that has at least 6 months until end of support. I am creating this issue to raise the awareness of the problem. Has work already been started to have a fix ready when end of support will be reached? I am guessing it is more work than just increasing the alpine version (no more Python 2 maybe?).

**Comment by hardillb** [comment]
There was a reason why it got pinned at 3.12, let me see if I can find the issue that caused it so we can re-evaluate

**Comment by hardillb** [comment]
PR: https://github.com/node-red/node-red-docker/pull/297
Issue: https://github.com/node-red/node-red-docker/issues/296

Root cause: https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements

The problem here is that to change this will force all 32bit ARM users to need to have docker at newer than 19.03.9.

We have Node-RED 3.0 coming up soon, that would be the right time to re-introduce the breaking change of a new Alpine base image and  this requirement

**Comment by hardillb** [comment]
We can not introduce a breaking change into an existing release stream, this will wait for 3.0

https://nodered.org/about/releases/

**Comment by candoumbe** [comment]
Hi everyone !
Any update on this issue ?
I saw the release timelime and still no `3.X.X` on sight 😭

**Comment by knolleary** [comment]
The first beta release of 3.0 is coming this week.

**Comment by hardillb** [comment]
Beta release is up `nodered/node-red-dev@v3.0.0-beta.1`
