### ISSUE TITLE
Different installation of Node-RED on Raspbian Jessie

### ISSUE THREAD

**Issue by makeacoffeeprj** [node-red/node-red-docker#36]
Hi everyone,

I'm trying to understand why the Node-RED installation that comes with the Raspbian Jessie OS has differences with the version you ship on Docker.
The first difference I can see is that on Raspbian there are more nodes available, i.e. "Watson IoT", "serial", "play audio", "smooth", but it doesn't have "base64", "msgpack", "sunrise" nodes that are available on the Docker version
For the Raspberry Pi specific nodes, the version on Raspbian has "ledborg" and "sensehat" that are not available on Docker.
Also the network node "ping" is available only on Raspbian.

Is it possible to provide the same user experience that is available on the base Raspbian?

Also the paths are different, the flows file is different and so on.

I would like to have also an interface for XBee, but my requirement maybe works just for me.

Thanks,

Diego

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

We preinstall a variety of non-core nodes on the Raspbian version as it is readily exposed to a much wider audience and we wanted to provide as rich an experience as possible without a user having to delve to the command line to start installing things. (This was done before we added the palette manager feature that makes it far easier to add nodes).

The docker version is a much more vanilla version - intended as the base starting point for a more technically oriented audience to be able to customise to their own needs.


Thanks!
