### ISSUE TITLE
Container created from latest image does not start

### ISSUE THREAD

**Issue by elvetemedve** [node-red/node-red-docker#39]
## The problem
Running the command `docker run -it -p 1880:1880 --name node-red nodered/node-red-docker` does not start the application, but fails with the following error message:

### Actual output
```
Error response from daemon: shim error: json: cannot unmarshal array into Go struct field processState.capabilities of type specs.LinuxCapabilities
```

### Expected output
```
Welcome to Node-RED
===================
```

## Environment
**Docker image ID:** 435384cc1753
**Node Red version:** 0.17.4
**Docker version:** 17.06.0-ce, build 3dfb8343
**Linux kernel version:** 4.11.9-1-ARCH
**OS:** Arch Linux

**Comment by jthomas** [comment]
Hello, other people are reporting this error due to Docker updates on Arch Linux. 
https://github.com/docker/for-linux/issues/49#issuecomment-315665552
https://github.com/docker/for-linux/issues/61

Looking at the error message, it appears to be the same issue.
```
Error response from daemon: shim error: json: cannot unmarshal array into Go struct field processState.capabilities of type specs.LinuxCapabilities
```

If you run other images, does the same issue occur? 

It looks like you'll have to wait for a new version of the Docker package for your operating system. 

Given this looks like an issue with Docker, rather than this image, I would propose closing this issue unless you believe there's anything we can do to resolve this?

**Comment by elvetemedve** [comment]
Hi @jthomas,

You are right, it's an issue with Docker itself. 
Surprisingly rebooting the machine fixed it. I think that's because I updated a lot of packages without restart. Probably new libraries were read from disk, but the old version was still in memory which caused conflict. But it's just a guess.

Anyway, thanks for the quick help.
