### ISSUE TITLE
Docker image with node 18.x core dumped

### ISSUE THREAD

**Issue by gray380** [node-red/node-red-docker#408]
Hello,

Docker service with 3.1 image works:
```
[info] Node-RED version: v3.1.3
[info] Node.js  version: v16.20.2
[info] Linux 4.18.0-425.19.2.el8_7.x86_64 x64 LE
``` 
Docker service with 3.1.3-18 (3.0.2-18 as well) core dumped:
```
./entrypoint.sh: line 14:     7 Illegal instruction     (core dumped) /usr/local/bin/node $NODE_OPTIONS node_modules/node-red/red.js --userDir /data $FLOWS "${@}"
```

### What are the steps to reproduce?
```
docker stack deploy --resolve-image=always --with-registry-auth --compose-file docker-compose.yml stackname
```
### What happens?
core dumped

### What do you expect to happen?
service up and running

### Please tell us about your environment:

[ ] Platform/OS:
```shell
cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.7 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.7"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.7 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.7"
```
[ ] Browser:
 
  - If you are a Portainer user, please attach a screenshot of your container details.
  
    ```
    Containers -> Click on the node-red container -> Scroll to Container Details and take a screenshot
    ```
    
  - If you are a command line user please execute the following command and attach the log file.

    ```shell
    docker inspect <container_id> > container.log
    ```

**Comment by hardillb** [comment]
We are going to need some more details here, to start with:

- Can we get more of the log running up to the failure
- What nodes do you have installed
- What version of docker are you using

**Comment by hardillb** [comment]
Also what is the output of the following command:

```
sudo scmp_sys_resolver -a arm clock_gettime64
```

**Comment by gray380** [comment]
I've changed the `package.json` in the /data from:
```json
{
    "name": "node-red-project",
    "description": "A Node-RED Project",
    "version": "0.0.1",
    "private": true
}
```
to the:
```
{
    "name": "node-red-docker",
    "version": "3.1.3",
    "description": "Low-code programming for event-driven applications",
    "homepage": "http://nodered.org",
    "license": "Apache-2.0",
    "repository": {
        "type": "git",
        "url": "https://github.com/node-red/node-red-docker.git"
    },
    "main": "node_modules/node-red/red/red.js",
    "scripts": {
        "start": "node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS",
        "debug": "node --inspect=0.0.0.0:9229 $NODE_OPTIONS node_modules/node-red/red.js $FLOWS",
        "debug_brk": "node --inspect=0.0.0.0:9229 --inspect-brk $NODE_OPTIONS node_modules/node-red/red.js $FLOWS"
    },
    "dependencies": {
        "node-red": "3.1.3",
        "node-red-contrib-mssql-plus": "~0.10.2",
        "node-red-contrib-redis": "~1.3.9",
        "node-red-contrib-uuid": "~0.0.4"
    },
    "engines": {
        "node": ">=14"
    }
}
```
and service has started.

To be honest I do not recall where `package.json` comes from.

**Comment by hardillb** [comment]
Just changing the package.json should not have caused node-red to fail to start.

Also `node-red` should not be listed in the dependencies for a `package.json` in `/data`

**Comment by gray380** [comment]
> Also what is the output of the following command:
> 
> ```
> sudo scmp_sys_resolver -a arm clock_gettime64
> ```

no such command

**Comment by gray380** [comment]
> Just changing the package.json should not have caused node-red to fail to start.
> 

miracle ...
That is the only change I've made.

> Also `node-red` should not be listed in the dependencies for a `package.json` in `/data`
>
I used [this](https://github.com/node-red/node-red-docker/blob/master/docker-custom/package.json) example.

**Comment by hardillb** [comment]
That file is for building the container, not for the userDir (`/data`)

Please supply the information I asked for re the versions and the docker-compose file you used

**Comment by gray380** [comment]
> That file is for building the container, not for the userDir (`/data`)
> 
so, what is the correct way to set dependencies?

> Please supply the information I asked for re the versions and the docker-compose file you used

**Comment by hardillb** [comment]
OK, so first you are not using the default image you are using a custom extended container you have built. So it is not the Node-RED images which are crashing but your extended container images, this would have been helpful to know upfront (this is why we ask for the `docker inspect` output, so we can see what container you are actually using).

The illegal instruction error implies that the container was built for a different target architecture than the one you are running on.

- Did you do a multi arch manifest build and push that to your local container repository?
- If you use the default Node-RED shipped image does it start?
- If you build the container locally on the machine it will run on does it start?

As for including dependencies:

> so, what is the correct way to set dependencies?

The file you pointed at lives in `/usr/src/node-red` this is where the code node-red app is installed in the container. If you edit that `package.json` to include dependencies then you need to rebuild the whole container. (which you could then use as a base for your extended container)

The other option is to add dependencies to the `package.json` in the `/data` volume and run `npm install` in that directory as part of you extended container. These will be copied to any empty volume mounted on `/data` when you start up the container for the first time.

At this point I'm not convinced there is a problem with Node-RED shipped containers and the problem is with your build/deployment environment.

**Comment by gray380** [comment]
This is alittle bit weird.
My image is based on the official image with added certificates and `crypto` npm package.

And yes, your images starts successfully:
```
docker run -it -v myNodeREDdata:/data --name mynodered nodered/node-red:3.1.3-18
30 Jan 16:55:44 - [info]

Welcome to Node-RED
===================

30 Jan 16:55:44 - [info] Node-RED version: v3.1.3
30 Jan 16:55:44 - [info] Node.js  version: v18.19.0
30 Jan 16:55:44 - [info] Linux 4.18.0-477.15.1.el8_8.x86_64 x64 LE
30 Jan 16:55:46 - [info] Loading palette nodes
```

**Comment by dceejay** [comment]
I think crypto indeed has a binary component so needs to be rebuilt for the correct architecture.
