### ISSUE TITLE
synology folder mount problem

### ISSUE THREAD

**Issue by moshe19803** [node-red/node-red-docker#56]
hi,
i am very new to docker world
I run docker on my Synology and I deploy this image without mounting folder in Synology and it works.
But I don't have access to the files in the container and any problem I have I need to reinstall.

i want to use, the Synology to mount option and link the folder in my nas so it will be the /data folder.
If I put /data as the mount path the container dosent start.

Any help on what to do?

**Comment by dceejay** [comment]
As per the overall project contribution guidelines we prefer how-to questions via either the Google group mailing list, the slack channel or via stack overflow tagged with node-red - that way the widest possible audience can see and help with your request, rather than have to rely on the limited time of the core developers.

**Comment by knolleary** [comment]
Closing due to lack of response. IF this is still a problem, please follow-up on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!
