### ISSUE TITLE
Noob question about how to install extra modules when start a fresh docker container.

### ISSUE THREAD

**Issue by kevinshane** [node-red/node-red-docker#66]
Hi guys, I would like to install some modules when creating a brand new docker container, I try to follow the github readme process but seems like nothing happen when I modify `package.json` file(in this case just a `bigtimer` node)
```
"dependencies": {
        "node-red": "0.18.4",
        "node-red-node-msgpack": "*",
        "node-red-node-base64": "*",
        "node-red-node-suncalc": "*",
        "node-red-node-random": "*",
        "node-red-contrib-bigtimer": "*"
    },
```
here is the docker command:
```
docker run --name=nodered --net=host --user=root --restart=always -d -v /opt/nodered:/data -v /opt/nodered/package.json:/usr/src/node-red/package.json -v /opt/nodered/settings.js:/data/settings.js nodered/node-red-docker:rpi 
```
what have I done something wrong here?
How am I suppose to create the new container and it auto install some modules for me?
Can I run some custom command when a container is created? like this in the beginning?
`apt-get install libavahi-compat-libdnssd-dev`

So sorry for the noob question, thanks

**Comment by knolleary** [comment]
Hi, thanks for raising an issue and apologies for the delay in responding.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!
