### ISSUE TITLE
suggestion: install CLI text editor

### ISSUE THREAD

**Issue by EZS-JD** [node-red/node-red-docker#78]
I'd like to suggest installing a CLI text editor like nano or vim as part of this docker image.
This would make it more straight-forward to change the settings.js file inside the container e.g.

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you read the Issue template you deleted before raising this, you'll see we prefer to handle feature requests on the [forum](https:/discourse.nodered.org) or [slack team](https://nodered.org/slack).

This allows the whole Node-RED user community to discuss, rather than rely on the core development team.


Thanks!

**Comment by EZS-JD** [comment]
oops sorry 'bout that.

**Comment by EZS-JD** [comment]
Where in the forum would I post issues pertaining to the node-red docker container?

**Comment by RaymondMouthaan** [comment]
Node-RED 1.0.0 is now available on docker hub - https://hub.docker.com/r/nodered/node-red.

This closes this issue, the images have nano installed.

There are a few changes to the new release, please read the [README](https://github.com/node-red/node-red-docker/blob/master/README.md) for further details.
