### ISSUE TITLE
Unable to install/use node-red-admin

### ISSUE THREAD

**Issue by crispy78** [node-red/node-red-docker#87]
### What are the steps to reproduce?
Install the NodeRED docker image on a Synology DS718+ (NAS) using the Docker-application that comes with the Synology NAS. Open a bash-terminal from within the container and try running "npm install -g node-red-admin"

### What happens?
It will output some errors because it doesn't have sufficient rights to /usr/local/lib/node_modules.
When trying to sudo the npm install command it cannot find sudo.
My data-folder is located and accessible on the NAS, NodeRED is able to read/write from/in this location.

### What do you expect to happen?
I would expect it to install node-red-admin on my docker NodeRED installation.

### Please tell us about your environment:

- [ ] Node-RED version: v. 0.19.4
- [ ] node.js version: v. 6.14.4
- [ ] npm version: v. 3.10.10
- [ ] Platform/OS: Synology DSM 6.2.1-23824
- [ ] Browser: Firefox 62.0.3 (64-bit), running on Windows 10

**Comment by dceejay** [comment]
when using -g it tries to write to the system directories as it reports - this is so it can add the node-red-admin command to the path... You can just install without -g - but then you will need to find the node-red-admin script under your node_modules/.bin directory and either execute it there or otherwise add it to your path.

Either that - or run the npm i -g command as root somehow so that it does have permissions to write to that directory (which is what sudo tries to do... but only if installed)

**Comment by jarlave** [comment]
use 
`docker exec -u 0 -it <container_name> bash`
to be root in the container, now `npm install -g` works

**Comment by dceejay** [comment]
Hopefully the above response is/was sufficient to close this old issue - please feel free to re-open if not.

**Comment by unholyhimura** [comment]
If someone else needs step-by-step on how to install Node-Red on a Synology NAS, there is this website that contains good instruction on how to do it. It also solves the permission issue:
[https://www.atomicha.com/synology-nas-docker-installing-node-red-part-1-node-red-requirements/](https://www.atomicha.com/synology-nas-docker-installing-node-red-part-1-node-red-requirements/)
