### ISSUE TITLE
Question: Tips for managing node ports

### ISSUE THREAD

**Issue by dougcooper** [node-red/node-red-docker#93]
I've been using nodered directly on ubuntu but recently decided to migrate my services to docker. I just realized that with nodered in a docker container I'm losing flexibility in node management if a new node brings in a unique port. Im not a docker power user by any means. Is there an easy way to manage the available ports that a docker container exposes? I was thinking either a DMZ (not preferred) or am hopeful that nodered has a built in broker for managing a range of ports that nodes have access to. Thanks in advance!

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [forum](https:/discourse.nodered.org) or [slack team](https://nodered.org/slack). If its a general how-to type question, you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`.

This allows the whole Node-RED user community to help, rather than rely on the core development team.

Thanks!

**Comment by dougcooper** [comment]
apologies. will do.

**Comment by dougcooper** [comment]
submitted to forum. thanks!
